### PR TITLE
bare-metal setup docs

### PR DESCRIPTION
**Pull request by pradykaushik**

### CODE REVIEW

**Comment by pradykaushik** [comment]
@SrinidhiRaghavendra could you please review this?

**Comment by pradykaushik** [comment]
@SrinidhiRaghavendra could you review this?

**Comment by SrinidhiRaghavendra** [comment]
> @SrinidhiRaghavendra could you review this?

PK, I'll review this on this weekend, testing the instructions on a remote machine.

**Comment by pradykaushik** [comment]
I don't think you'll be able to test the instructions on any of the binghamton remote machines as you don't have superuser privileges.

**Comment by pradykaushik** [comment]
@SrinidhiRaghavendra what's the status on this?

**Review by SrinidhiRaghavendra — APPROVED** [review]

**Pull request merged**
